import { readFileSync } from 'fs';
import { resolve } from 'path';
import { describe, expect, it } from 'vitest';

const COMMAND = 'optimize_cover_thumbnails';
const PERMISSION = 'allow-optimize-cover-thumbnails';

const buildScript = readFileSync(resolve(process.cwd(), 'src-tauri/build.rs'), 'utf-8');
const rustCommandRegistry = readFileSync(resolve(process.cwd(), 'src-tauri/src/lib.rs'), 'utf-8');
const generatedPermission = readFileSync(
  resolve(process.cwd(), 'src-tauri/permissions/autogenerated/optimize_cover_thumbnails.toml'),
  'utf-8',
);
const manifestCommandBlock =
  buildScript.match(/AppManifest::new\(\)\.commands\(&\[(?<commands>[\s\S]*?)\]\)/)?.groups?.[
    'commands'
  ] ?? '';
const manifestCommands = Array.from(
  manifestCommandBlock.matchAll(/"(?<command>[a-z0-9_]+)"/g),
  (match) => match.groups?.['command'],
).filter((command): command is string => command !== undefined);

const readCapabilityPermissions = (file: string): string[] => {
  const capability = JSON.parse(
    readFileSync(resolve(process.cwd(), `src-tauri/capabilities/${file}`), 'utf-8'),
  ) as { permissions: Array<string | { identifier: string }> };

  return capability.permissions.map((entry) =>
    typeof entry === 'string' ? entry : entry.identifier,
  );
};

describe('cover thumbnail app-command ACL (#5632)', () => {
  it('declares the command in the Tauri app manifest', () => {
    expect(manifestCommands).toContain(COMMAND);
    expect(rustCommandRegistry).toContain('cover_thumbnail::optimize_cover_thumbnails');
    expect(generatedPermission).toContain(`commands.allow = ["${COMMAND}"]`);
  });

  it('grants the command to local app windows', () => {
    expect(readCapabilityPermissions('default.json')).toContain(PERMISSION);
  });

  it('grants the command to the webdriver Tauri test window', () => {
    expect(readCapabilityPermissions('webdriver-remote.json')).toContain(PERMISSION);
  });
});
